sudo: false

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
    include:
        - os: linux
          addons:
              apt:
                  packages:
                      - libgmp-dev
          before_install:
          - mkdir -p ~/.local/bin
          - export PATH=$HOME/.local/bin:$PATH
          - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
    - stack setup
    - stack exec -- ghc --version
    - stack build

script:
- stack test
